apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-radix
  labels:
    name: parsec-radix
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:splash2x_radix
        name: parsec-radix
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 7 ./run -a run -S splash2x -p radix -i native -n 1"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
        