apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes
  labels:
    name: parsec-blackscholes
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_blackscholes
        name: parsec-blackscholes
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 7 ./run -a run -S parsec -p blackscholes -i native -n 1"] # pin parsec.blackscholes benchmark to core 7 using 1 thread
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"